Repository junseokho/cptm.net, pull requests merged in 2024-10, with the labels that each got.

#2 [Build] 프론트엔드(vite+react) 프로젝트 추가 (/src/main/frontend)
  src/main/frontend/.gitignore
  src/main/frontend/README.md
  src/main/frontend/eslint.config.js
  src/main/frontend/index.html
  src/main/frontend/jsdoc.conf
  src/main/frontend/package.json
  src/main/frontend/public/vite.svg
  src/main/frontend/src/App.css
  src/main/frontend/src/App.jsx
  src/main/frontend/src/apis/README.md
  src/main/frontend/src/assets/react.svg
  src/main/frontend/src/components/README.md
  src/main/frontend/src/index.css
  src/main/frontend/src/main.jsx
  src/main/frontend/vite.config.js
Labels: documentation, build, dependencies

#4 백엔드 체스방 생성 풀리퀘
  build.gradle
  src/main/java/com/example/chessdotnet/config/DataInitializer.java
  src/main/java/com/example/chessdotnet/config/SecurityConfig.java
  src/main/java/com/example/chessdotnet/controller/RoomController.java
  src/main/java/com/example/chessdotnet/dto/CreateRoomRequest.java
  src/main/java/com/example/chessdotnet/dto/JoinRoomRequest.java
  src/main/java/com/example/chessdotnet/dto/LeaveRoomRequest.java
  src/main/java/com/example/chessdotnet/dto/RoomDTO.java
  src/main/java/com/example/chessdotnet/dto/UserDTO.java
  src/main/java/com/example/chessdotnet/entity/Room.java
  src/main/java/com/example/chessdotnet/entity/User.java
  src/main/java/com/example/chessdotnet/exception/RoomNotFoundException.java
  src/main/java/com/example/chessdotnet/exception/UserNotFoundException.java
  src/main/java/com/example/chessdotnet/exception/UserNotInRoomException.java
  src/main/java/com/example/chessdotnet/repository/RoomRepository.java
  src/main/java/com/example/chessdotnet/repository/UserRepository.java
  src/main/java/com/example/chessdotnet/service/RoomService.java
  src/main/resources/application.properties
  src/test/java/com/example/chessdotnet/ChessDotNetApplicationTests.java
  src/test/java/com/example/chessdotnet/config/DataInitializerTest.java
  src/test/java/com/example/chessdotnet/config/SecurityConfigTest.java
  src/test/java/com/example/chessdotnet/controller/RoomControllerTest.java
  src/test/java/com/example/chessdotnet/dto/CreateRoomRequestTest.java
  src/test/java/com/example/chessdotnet/dto/JoinRoomRequestTest.java
  src/test/java/com/example/chessdotnet/dto/RoomDTOTest.java
  src/test/java/com/example/chessdotnet/repository/RoomRepositorySpringTest.java
  src/test/java/com/example/chessdotnet/repository/RoomRepositoryTest.java
  src/test/java/com/example/chessdotnet/repository/UserRepositoryTest.java
  src/test/java/com/example/chessdotnet/service/RoomServiceTest.java
Labels: documentation, enhancement, build, dependencies

#8 기물 색 정하기
  src/main/java/com/example/chessdotnet/controller/RoomController.java
  src/main/java/com/example/chessdotnet/dto/CreateRoomRequest.java
  src/main/java/com/example/chessdotnet/dto/RoomDTO.java
  src/main/java/com/example/chessdotnet/entity/Room.java
  src/main/java/com/example/chessdotnet/entity/User.java
  src/main/java/com/example/chessdotnet/service/RoomService.java
  src/test/java/com/example/chessdotnet/ChessDotNetApplicationTests.java
  src/test/java/com/example/chessdotnet/config/SecurityConfigTest.java
  src/test/java/com/example/chessdotnet/controller/RoomControllerTest.java
  src/test/java/com/example/chessdotnet/dto/CreateRoomRequestTest.java
  src/test/java/com/example/chessdotnet/dto/RoomDTOTest.java
  src/test/java/com/example/chessdotnet/repository/RoomRepositorySpringTest.java
  src/test/java/com/example/chessdotnet/repository/RoomRepositoryTest.java
  src/test/java/com/example/chessdotnet/service/RoomServiceTest.java
Labels: bug, enhancement

#6 [build, deps, feat] Lobby 컴포넌트 구현/Lobby 관련 API 요청 메소드 추가/SCSS 라이브러리 추가
  src/main/frontend/jsdoc.conf
  src/main/frontend/package.json
  src/main/frontend/src/apis/MatchAPI.js
  src/main/frontend/src/assets/css/lobby.scss
  src/main/frontend/src/components/Lobby.jsx
  src/main/frontend/vite.config.js
Labels: documentation, enhancement, build, dependencies
