Repository junseokho/cptm.net, pull requests merged in 2024-11, with the labels that each got.

#9 [feat] 로비 메뉴 / 로비 UI 변경 / 메인 화면 Layout
  src/main/frontend/src/apis/MatchAPI.js
  src/main/frontend/src/assets/css/lobby.scss
  src/main/frontend/src/assets/css/main_layout.scss
  src/main/frontend/src/components/Lobby.jsx
  src/main/frontend/src/components/Main.jsx
  src/main/frontend/src/main.jsx
Labels: bug, enhancement

#10 비회원 생성 기능 및 기물 움직임 저장 기능
  README.md
  build.gradle
  src/main/java/com/example/chessdotnet/config/SecurityConfig.java
  src/main/java/com/example/chessdotnet/config/websocket/StompMessageTraceInterceptor.java
  src/main/java/com/example/chessdotnet/config/websocket/WebSocketConfig.java
  src/main/java/com/example/chessdotnet/config/websocket/WebSocketConnectionHandler.java
  src/main/java/com/example/chessdotnet/controller/ChessGameController.java
  src/main/java/com/example/chessdotnet/controller/RoomController.java
  src/main/java/com/example/chessdotnet/controller/UserController.java
  src/main/java/com/example/chessdotnet/dto/ChessMoveDTO.java
  src/main/java/com/example/chessdotnet/dto/CreateRoomRequest.java
  src/main/java/com/example/chessdotnet/dto/CreateUserRequest.java
  src/main/java/com/example/chessdotnet/dto/RoomStatusMessage.java
  src/main/java/com/example/chessdotnet/entity/ChessGame.java
  src/main/java/com/example/chessdotnet/entity/User.java
  src/main/java/com/example/chessdotnet/exception/GameEndedException.java
  src/main/java/com/example/chessdotnet/exception/IllegalMoveException.java
  src/main/java/com/example/chessdotnet/exception/InvalidGameStateException.java
  src/main/java/com/example/chessdotnet/exception/InvalidTurnException.java
  src/main/java/com/example/chessdotnet/repository/ChessGameRepository.java
  src/main/java/com/example/chessdotnet/service/ChessGameService.java
  src/main/java/com/example/chessdotnet/service/RoomService.java
  src/main/java/com/example/chessdotnet/service/RoomWebSocketService.java
  src/main/java/com/example/chessdotnet/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/example/chessdotnet/config/DataInitializerTest.java
  src/test/java/com/example/chessdotnet/config/WebSocketIntegrationTest.java
  src/test/java/com/example/chessdotnet/config/WebSocketServiceTest.java
  src/test/java/com/example/chessdotnet/service/ChessGameServiceTest.java
  src/test/java/com/example/chessdotnet/service/RoomServiceTest.java
Labels: bug, enhancement

#11 [Fix, Refactor] 체스보드 컴포넌트 재설계 / `utils` 모듈 추가 / class `Piece` 내부 메소드, 멤버에서 버그 수정
  src/main/frontend/src/components/ChessBoard.jsx
  src/main/frontend/src/components/ChessBoardLogic.jsx
  src/main/frontend/src/components/Piece.jsx
  src/main/frontend/src/components/Square.jsx
  src/main/frontend/src/components/initialChessBoard.js
  src/main/frontend/src/utils/utils.js
  src/main/resources/application.properties
Labels: bug, enhancement

#14 [Feature] 체스 게임 WebSocket 컨트롤러(ChessGameController)에 기권 기능 추가 및 기물 이동 로직 개선
  src/main/java/com/example/chessdotnet/controller/ChessGameController.java
  src/main/java/com/example/chessdotnet/dto/RoomDTO.java
  src/main/java/com/example/chessdotnet/entity/Room.java
  src/main/java/com/example/chessdotnet/repository/RoomRepository.java
  src/main/java/com/example/chessdotnet/service/RoomService.java
  src/test/java/com/example/chessdotnet/service/ChessGameServiceTest.java
  src/test/java/com/example/chessdotnet/service/RoomServiceTest.java
Labels: feat

#19 feat: 백엔드에서의 Chessboard 이동 규칙 검증을 위한 `class Chessboard` 추가
  src/main/java/com/example/chessdotnet/service/chessGameSession/Bishop.java
  src/main/java/com/example/chessdotnet/service/chessGameSession/Chessboard.java
  src/main/java/com/example/chessdotnet/service/chessGameSession/ChessboardMove.java
  src/main/java/com/example/chessdotnet/service/chessGameSession/ChessboardPos.java
  src/main/java/com/example/chessdotnet/service/chessGameSession/King.java
  src/main/java/com/example/chessdotnet/service/chessGameSession/Knight.java
  src/main/java/com/example/chessdotnet/service/chessGameSession/Pawn.java
  src/main/java/com/example/chessdotnet/service/chessGameSession/Piece.java
  src/main/java/com/example/chessdotnet/service/chessGameSession/Queen.java
  src/main/java/com/example/chessdotnet/service/chessGameSession/README.md
  src/main/java/com/example/chessdotnet/service/chessGameSession/Rook.java
  src/test/java/com/example/chessdotnet/service/chessGameSession/ChessboardTest.java
  src/test/java/com/example/chessdotnet/service/chessGameSession/ChessboardTest.md
Labels: feat, test
